## Health Check
GET http://localhost:8080/api/health


### Register User
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name": "Dian",
    "email": "dian@example.com",
    "password": "password123"
}

### Login User
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "dian@example.com",
    "password": "password123"
}


### Me 
GET http://localhost:8080/api/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMU00MTBZQ0dWNUFSMEZCTk5XMEZDNlczMCIsImV4cCI6MTc5MTA4NDc3MX0.aIMtGWGfq8ITN8lDI_kn-4ZtVk2SgfjOaENhN0qeOho