@baseUrl = http://localhost:8080
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMU00MTBZQ0dWNUFSMEZCTk5XMEZDNlczMCIsImV4cCI6MTc5MTA5Njc2M30.L6q2iUwgxxsnSceNvdrqwshwBvlGXz634MZgjA6o9tM

### Health Check
GET {{baseUrl}}/api/health

### Register User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "name": "Dian",
    "email": "dian@example.com",
    "password": "password123"
}

### Login User
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "dian@example.com",
    "password": "password123"
}

### Me Profile
GET {{baseUrl}}/api/me
Authorization: Bearer {{token}}

### Create Category - Expense
POST {{baseUrl}}/api/categories
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Makan",
    "category_type": "expense"
}

### Get All Categories
GET {{baseUrl}}/api/categories
Authorization: Bearer {{token}}

### Update Category (Gunakan method PUT dan kirimkan ID category di URL)
PUT {{baseUrl}}/api/categories/01M42GHZ2NMJ9HW0MB9V8S6VDG
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Sedekah"
}

### Delete Category (Gunakan method DELETE dan kirimkan ID category di URL)
DELETE {{baseUrl}}/api/categories/01M42GHZ2NMJ9HW0MB9V8S6VDG
Authorization: Bearer {{token}}